# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_term', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('HEB', 'Hebrew'), ('ARAM', 'Aramaic'), ('LW', 'Loanword')], default='HEB', max_length=2)),
                ('page_number', models.IntegerField(blank=True)),
            ],
        ),
    ]
