# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20170424_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='part_of_speech',
            field=models.CharField(choices=[('VERB', 'Verb'), ('NOUN', 'Noun'), ('ADJ', 'Adjective'), ('PREP', 'Preposition'), ('ADV', 'Adverb'), ('OTHER', 'Other')], default='NOUN', max_length=5),
        ),
    ]
