# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcard_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='root',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
