# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_flashcard_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
