# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_flashcard_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='page_number',
        ),
    ]
