# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_remove_flashcard_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='page_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
