# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_auto_20170514_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='loanword_language',
            field=models.TextField(blank=True),
        ),
    ]
