# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0010_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='flashcard',
            new_name='flashcards',
        ),
    ]
